In [1]:
import sqlite3
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
monster_job_sample = pd.read_csv("../data/monster_job_sample.csv",index_col=0)

In [3]:
monster=monster_job_sample.copy()

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
monster.head()

,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
country,,,,,,,,,,,,,
United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c

In [10]:
monster.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22000 entries, United States of America to United States of America
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country_code     22000 non-null  object
 1   date_added       122 non-null    object
 2   has_expired      22000 non-null  object
 3   job_board        22000 non-null  object
 4   job_description  22000 non-null  object
 5   job_title        22000 non-null  object
 6   job_type         20372 non-null  object
 7   location         22000 non-null  object
 8   organization     15133 non-null  object
 9   page_url         22000 non-null  object
 10  salary           3446 non-null   object
 11  sector           16806 non-null  object
 12  uniq_id          22000 non-null  object
dtypes: object(13)
memory usage: 2.9+ MB

In [7]:
monster.describe().T

,count,unique,top,freq
country_code,22000,1,US,22000
date_added,122,78,9/22/2016,6
has_expired,22000,1,No,22000
job_board,22000,1,jobs.monster.com,22000
job_description,22000,18744,12N Horizontal Construction Engineers Job Desc...,104
job_title,22000,18759,Monster,318
job_type,20372,39,Full Time,6757
location,22000,8423,"Dallas, TX",646
organization,15133,738,Healthcare Services,1919
page_url,22000,22000,http://jobview.monster.com/it-support-technici...,1
salary,3446,1737,"40,000.00 - 100,000.00 $ /year",50
sector,16806,163,Experienced (Non-Manager),4594
uniq_id,22000,22000,11d599f229a80023d2f40e7c52cd941e,1